from __future__ import annotations

from typing import Any, List, Tuple
from dataclasses import dataclass

from IArena.interfaces.IPlayer import IPlayer
from IArena.arena.GenericGame import ClockGame
from IArena.grader.RulesGenerator import IRulesGenerator, RulesGeneratorSuite
from IArena.utils.YamlMixing import YamlMixing
from IArena.utils.printing import green_tick, red_cross
from IArena.games.solvers.Solver import Solver, get_solver_from_name



@dataclass(init=False)
class ReportCommonConfiguration(YamlMixing):
    """
    Common configurations of a report that are not related to the rules generation.
    This class is generated by a yaml dictionary.
    """

    move_timeout_s: float = 5
    total_timeout_s: float = 10
    max_score: float = None
    min_score: float = None
    repetitions: int = 1
    fails_allowed: int = 0
    max_moves: int = 1000
    solver_configuration: dict = None  # Preferred YAML key for solver configuration
    solver: dict = None  # Backward-compatible YAML key
    _solver: Solver = None

    def use_solver(self) -> bool:
        return (self.max_score is None or self.min_score is None) and self.solver_configuration_data() is not None

    def solver_instance(self):

        if self._solver is not None:
            return self._solver

        conf = self.solver_configuration_data()
        if conf is None:
            raise ValueError("Solver configuration is not set, but use_solver() is True.")

        self._solver = get_solver_from_name(
            name=conf["name"],
            args=conf["args"],
        )
        return self._solver

    def solver_configuration_data(self) -> dict | None:
        conf = self.solver_configuration
        if conf is None:
            conf = self.solver
        if conf is None:
            return None
        if not isinstance(conf, dict):
            raise ValueError(f"Solver configuration must be a dictionary, got: {type(conf)}")

        # Support both {"name": "..."} and {"class": "..."} keys in YAML.
        name = conf.get("name")
        if name is None:
            name = conf.get("class")
        if name is None:
            raise ValueError("Solver configuration must include either 'name' or 'class'.")

        args = conf.get("args", {})
        if args is None:
            args = {}
        if not isinstance(args, dict):
            raise ValueError(f"Solver 'args' must be a dictionary, got: {type(args)}")

        return {
            "name": name,
            "args": args,
        }

    def solver_cache_signature(self) -> Tuple[str, tuple[tuple[str, Any], ...]]:
        conf = self.solver_configuration_data()
        if conf is None:
            return ("", ())
        return (
            conf["name"],
            Report._freeze(conf["args"]),
        )


@dataclass
class ReportResult:
    """
    Result for a report with its multiple configurations and repetitions.
    """

    successes: List[bool]
    messages: List[str]
    warnings: List[str]
    errors: List[str]

    def total(self) -> int:
        return len(self.successes)
    def passed(self) -> int:
        return sum(1 for s in self.successes if s)
    def failed(self) -> int:
        return sum(1 for s in self.successes if not s)


    def minimum_result(result1: ReportResult, result2: ReportResult) -> ReportResult:
        """
        Combine two ReportResults taking the minimum result for each field.
        """
        combined_successes = [s1 and s2 for s1, s2 in zip(result1.successes, result2.successes)]
        combined_messages = result1.messages + result2.messages
        combined_warnings = result1.warnings + result2.warnings
        combined_errors = result1.errors + result2.errors

        return ReportResult(
            successes=combined_successes,
            messages=combined_messages,
            warnings=combined_warnings,
            errors=combined_errors,
        )

    def __eq__(self, value):
        return self.successes == value.successes


class Report:
    """
    Class that represents a specific configuration or test for a given Game and Player.

    It contains common configurations and a suite of game configurations for the rules generator.
    It runs multiple games with different configurations and repetitions, and collects the results.
    """

    # Cache solver scores globally for this process.
    # Keyed by (rules_generator_class, solver signature, concrete configuration).
    _SOLVER_SCORE_CACHE = {}

    def __init__(
                self,
                rules_generator: IRulesGenerator,
                player: IPlayer,
                common_configuration: ReportCommonConfiguration,
                rules_suite: RulesGeneratorSuite,
            ):

        self._rules_generator : IRulesGenerator = rules_generator
        self._player : IPlayer = player
        self._common_configuration : ReportCommonConfiguration = common_configuration
        self._rules_suite : RulesGeneratorSuite = rules_suite

        self._result = None
        self._inconsistency = False

    @staticmethod
    def _freeze(value: Any):
        """Convert nested structures into hashable deterministic tuples."""
        if isinstance(value, dict):
            return tuple(sorted((str(k), Report._freeze(v)) for k, v in value.items()))
        if isinstance(value, (list, tuple)):
            return tuple(Report._freeze(v) for v in value)
        if isinstance(value, set):
            return tuple(sorted(Report._freeze(v) for v in value))
        return value

    def _resolve_score_limits(
                self,
                conf: dict,
                rules,
            ) -> tuple[float, float]:
        min_score = self._common_configuration.min_score
        max_score = self._common_configuration.max_score

        if not self._common_configuration.use_solver():
            return (
                float("-inf") if min_score is None else min_score,
                float("inf") if max_score is None else max_score,
            )

        cache_key = (
            self._rules_generator.__class__.__module__,
            self._rules_generator.__class__.__name__,
            self._common_configuration.solver_cache_signature(),
            Report._freeze(conf),
        )

        if cache_key not in Report._SOLVER_SCORE_CACHE:
            solver = self._common_configuration.solver_instance()
            Report._SOLVER_SCORE_CACHE[cache_key] = solver.min_max_allowed_score(rules)

        solver_min, solver_max = Report._SOLVER_SCORE_CACHE[cache_key]
        if min_score is None:
            min_score = solver_min
        if max_score is None:
            max_score = solver_max

        return min_score, max_score


    def run(
                self,
                debug: bool = False,
            ) -> ReportResult:

        if self._result is None:
            self._result = self._run(debug=debug)

        else:
            result = self._run(debug=debug)

            if result != self._result:
                self._inconsistency = True
            self._result = ReportResult.minimum_result(self._result, result)

        return self._result


    def _run(
                self,
                debug: bool = False,
            ) -> ReportResult:

        successes = []
        messages = []
        warnings = []
        errors = []

        for conf in self._rules_suite.get_configuration_iterator():

            rules = self._rules_generator.generate(conf)

            min_score, max_score = self._resolve_score_limits(conf=conf, rules=rules)

            for i in range(self._common_configuration.repetitions):

                game = ClockGame(
                            rules,
                            [self._player],
                            move_timeout_s=self._common_configuration.move_timeout_s,
                            total_timeout_s=self._common_configuration.total_timeout_s,
                            max_moves=self._common_configuration.max_moves,
                        )

                correct_execution = True
                try:
                    score = game.play()[0]
                except Exception as e:
                    correct_execution = False
                    successes.append(False)
                    errors.append(f"Game crashed with conf {conf} repetition {i+1}: {{{e}}}")

                if correct_execution:
                    if score >= min_score:
                        successes.append(True)
                        if score > max_score:
                            warnings.append(f"Score {score} above max {max_score} with conf {conf} repetition {i+1}")

                    else:
                        successes.append(False)
                        if score < min_score:
                            messages.append(f"Score {score} below min {min_score} with conf {conf} repetition {i+1}")

                if debug:
                    if successes[-1]:
                        print(green_tick(), end="", flush=True)  # green small check
                    else:
                        print(red_cross(), end="", flush=True)  # red small cross


        _result = ReportResult(
                successes=successes,
                messages=messages,
                warnings=warnings,
                errors=errors,
            )

        return _result


    def get_result(self) -> ReportResult:
        if self._result is None:
            raise RuntimeError("Grader has not been run yet. Please run the grader before getting the result.")
        return self._result


    def calculate_grade(self) -> float:
        """
        Calculate grade according to:
        Max grade = 1
        Min grade = 0

        Each failure reduces the grade by 1 / (1+fails_allowed)

        Example:
        - If fails_allowed = 0, any failure results in a grade of 0.
        - If fails_allowed = 1, one failure results in a grade of 0.5, two or more failures result in a grade of 0.
        - If fails_allowed = 2, one failure results in a grade of 0.67, ...
        etc.
        """
        if self._result is None:
            raise RuntimeError("Grader has not been run yet. Please run the grader before calculating the final grade.")

        if self._result.total() == 0:
            return 0.0

        penalty_per_fail = 1.0 / (1 + self._common_configuration.fails_allowed)
        grade = 1.0 - (self._result.failed() * penalty_per_fail)
        if grade < 0.0:
            grade = 0.0
        return grade

    def has_inconsistency(self) -> bool:
        return self._inconsistency
