@startuml

skinparam MessageAlign center

actor User as "External Entity"
participant ARENA as "ARENA\nGame Engine"
participant RULES as "RULES\nGame Rules"
participant PLAYER as "PLAYER\nPlayer AI/User Interface"

title Game loop for autonomous agents

== Configuration ==
User -> ARENA : play(rules, players, view)

== Game Start ==
activate ARENA

ARENA -> PLAYER : starting_game(rules, player_index)
PLAYER --> ARENA : ready

ARENA -> RULES : first_position()
activate RULES
RULES --> ARENA : p0
deactivate RULES

== Turn Loop ==
loop while not is_finished(p0)

    ARENA -> PLAYER : play(p0)
    activate PLAYER
    PLAYER --> ARENA : mov
    deactivate PLAYER

    ARENA -> RULES : next_position(pos=p0, mov=mov)
    activate RULES
    RULES --> ARENA : p1
    deactivate RULES

    ARENA -> RULES : is_finished(pos=p1)
    activate RULES
    RULES --> ARENA : isFinished
    deactivate RULES

    note right of ARENA: Logic: p0 = p1 for next turn
end loop

== Game End ==

ARENA -> RULES : get_score(pos=p1)
activate RULES
RULES --> ARENA : score
deactivate RULES

ARENA --> User : score
deactivate ARENA

@enduml
