@startuml

skinparam MessageAlign center

actor User as "User/External"
participant APP as "APP\n(terminal)"
participant VIEW as "VIEW\n(TerminalView)"
participant ARENA as "ARENA\n(Arena)"
participant GAME as "GAME\n(Game)"
participant RULES as "RULES\n(Logic)"
participant PLAYER as "PLAYER\n(PolyvalentTerminalPlayer)"

title Generic game loop with visualization and human interaction

== Initialization ==
User -> APP : run
activate APP
activate VIEW

== Game configuration ==

APP -> User : ask_for_game()
activate User
User --> APP : game
deactivate User

APP -> User : ask_for_configuration()
activate User
User --> APP : configuration
deactivate User

APP -> User : ask_for_player()
activate User
User --> APP : player
deactivate User

APP -> GAME : generate_rules(configuration)
activate GAME
GAME --> APP : rules
deactivate GAME

APP -> ARENA : play(rules, players, view)
activate ARENA

ARENA -> PLAYER : starting_game(rules, player_index)
activate PLAYER
PLAYER --> ARENA : ready
deactivate PLAYER

ARENA -> RULES : first_position()
activate RULES

RULES --> ARENA : p0
deactivate RULES

== Game Loop ==
loop while not is_finished

    ' 1. Rendering Phase
    ARENA -> VIEW : render_state(p0, canvas)
    activate VIEW
    note right: Terminal rendering
    VIEW --> ARENA : done
    deactivate VIEW

    ' 2. Input Phase
    ARENA -> PLAYER : play(p0)
    activate PLAYER
    PLAYER -> VIEW : capture_input(raw_input)
    activate VIEW

    VIEW -> User : input()
    activate User
    User --> VIEW : mov
    deactivate User

    VIEW --> PLAYER : mov
    deactivate VIEW
    PLAYER --> ARENA : mov
    deactivate PLAYER

    ' 3. Logic Phase
    ARENA -> RULES : next_position(p0, mov)
    activate RULES
    RULES --> ARENA : p1
    deactivate RULES

    ARENA -> RULES : is_finished(p1)
    activate RULES
    RULES --> ARENA : isFinished
    deactivate RULES

    note right of ARENA: p0 = p1
end loop

== Termination ==

ARENA -> RULES : get_score(p1)
activate RULES
RULES --> ARENA : score
deactivate RULES

ARENA --> APP : score
deactivate ARENA

APP -> VIEW : render_info(rules, canvas)
APP -> VIEW : render_state(p1, canvas)

deactivate VIEW
deactivate APP

@enduml
